### ISSUE TITLE
babel and webpack problems

### ISSUE THREAD

**Issue by mosaab87** [125m125/splconfigurator#174]
WebpackOptionsValidationError: Invalid configuration object. Webpack has been initialised using a configuration object that does not match the API schema.
 - configuration.module has an unknown property 'loaders'. These properties are valid:
   object { defaultRules?, exprContextCritical?, exprContextRecursive?, exprContextRegExp?, exprContextRequest?, noParse?, rules?, strictExportPresence?, strictThisContextOnImports?, unknownContextCritical?, unknownContextRecursive?, unknownContextRegExp?, unknownContextRequest?, unsafeCache?, wrappedContextCritical?, wrappedContextRecursive?, wrappedContextRegExp? }
   -> Options affecting the normal modules (`NormalModuleFactory`).
    at webpack (C:\Users\MOSAA\Desktop\projects\git-travel\node_modules\webpack\lib\webpack.js:31:9)
    at Gulp.<anonymous> (C:\Users\MOSAA\Desktop\projects\git-travel\gulp\tasks\scripts.js:5:3)
    at module.exports (C:\Users\MOSAA\Desktop\projects\git-travel\node_modules\orchestrator\lib\runTask.js:34:7)
    at Gulp.Orchestrator._runTask (C:\Users\MOSAA\Desktop\projects\git-travel\node_modules\orchestrator\index.js:273:3)
    at Gulp.Orchestrator._runStep (C:\Users\MOSAA\Desktop\projects\git-travel\node_modules\orchestrator\index.js:214:10)
    at Gulp.Orchestrator.start (C:\Users\MOSAA\Desktop\projects\git-travel\node_modules\orchestrator\index.js:134:8)
    at C:\Users\MOSAA\Desktop\projects\git-travel\gulp\tasks\watch.js:23:10
    at write (C:\Users\MOSAA\Desktop\projects\git-travel\node_modules\gulp-watch\index.js:148:3)
    at C:\Users\MOSAA\Desktop\projects\git-travel\node_modules\gulp-watch\index.js:131:5
    at <anonymous>

when i use babel and it's not working

**Comment by mosaab87** [comment]
const path = require('path');


module.exports = {

    entry: "./app/assets/scripts/app.js",
    output: {
    filename: "app-bundle.js",
    path: path.resolve(__dirname, './app/temp/scripts')
  },
  module: {
           loaders: [
               {
                   test: /\.js$/,
                   loader: 'babel-loader',
                   query: {
                       presets: ['es2015']
                   }
               }
           ]
       }
};


and this is webpack.config.js file and i don't know where is the problem

**Comment by 125m125** [comment]
It seems like you already fixed this problem in your repository. It also seems like you are not using this configurator in your project, so you might have created this issue in the wrong repository?
